### PR TITLE
V2: Update readme links

### PR DESCRIPTION
**Pull request by abdullahtariq1171**
Hey @mechanicles , 

Just updated readme file to added links for quick navigation. 

Demo: https://github.com/abdullahtariq1171/ruby_simple_search/blob/v2/README.md#patterns

### CODE REVIEW

**Comment by abdullahtariq1171** [comment]
Actually, I noticed the order of features at top of the file doesn't follow the same order in which they are listed in detail. Shouldn't both have same ordering for better reading? 

Like `Search using patterns` is 3rd in list but it is first one in feature examples.

**Comment by mechanicles** [comment]
@abdullahtariq1171 Yes they should be in the same order. I might have missed that. Please go ahead and fix it :)

**Comment by mechanicles** [comment]
@abdullahtariq1171 Merged 👍Thanks for making this gem great!

**Comment by abdullahtariq1171** [comment]
@mechanicles my pleasure. 
I missed my last fix by few seconds :( 

heading of **Simple search returns an `ActiveRecord::Relation`** doesn't change to link in my last PR.

Submitted here again: https://github.com/mechanicles/ruby_simple_search/pull/8

**Pull request merged**
